### ISSUE TITLE
Larger fixed node stucks the cluster function from iterating

### ISSUE THREAD

**Issue by Dinple** [choltz95/Eigenvalue-problem-plus-linear-constraints#1]
Please checkout the `yuw-test branch `and run `rayleigh-testing `to see the problem.

- Both `Graph_1` and `Graph_random_12` have this problem. you might need to set the path to` testcases(exp only) `to generate Graph_1 correctly.

- Here is the issue. When generating my own fixed nodes, I set the `multiplier` to a large number. This will cause the algorithm to stuck after a few iteration and even crash the core sometimes. However, I haven't been able to find a `multipler` that is large enough to stuck the original input (from the website). This issue only occurs in my own generated graphs.

**Comment by choltz95** [comment]
Hey @Dinple, this is interesting. Could you quickly verify if the hangup is the projection operation in ```cluster(...)```? Right before the method assertion.

Or is the algorithm definitely able to enter/perform iterations in the newton loop?

**Comment by Dinple** [comment]
The projection operation in cluster right before the method assertion correctly outputs `X_k_n`. It should be a problem with the iteration because the progress bar shows up almost everytime.

Just a little more detail about the output `X_k_n`:
When running on 50 nodes and fixing the first 3 nodes, `X_k_n` has a dimension of (46,2).
When running on 12 nodes and fixing the first 3 nodes, `X_k_n` has a dimension of (8,2).

For cluster parameters I have:
cluster(rng, (opt_init, opt_update, get_params), 
                 X_k, np.array(flist_p), L, mapped_vars, fixed_indices=None, c1=c1, c2=c2, c3=c3, centercons=v.sum()*jnp.array([0,0]), 
                 v=None, D=None, eps=1e-8, maxiters=100, convergence_criterion=1e-3, method=method)

Let me know if you need any further details.

**Comment by Dinple** [comment]
Just did some testing on the `ssm` method. Sine it depends on `pnd()`, the issue persists.
Specifically, here are the lowest multiplier integer values that will stuck the algorithm:
50 ndoes -> `multiplier = 9`
12 nodes -> `multiplier = 5`

I will continue with more testing on the code. Hope this helps!
